language: python
python:
  - "3.6.4"
install:
  - pip install pytest
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest-cov
script:
  - python -m pytest
  - pytest --cov
after_success:
  - coveralls
