language: python
python:
  - "3.6.4"
install:
  - pip install pytest
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest-cov
services:
  - postgresql
# env:
#   global:
#   - app.config["TESTING"] = True
before_script:
  - psql -c 'create database manager;' -U postgres
  - psql -c 'create database test_db;' -U postgres
script:
  - python -m pytest
  - pytest --cov
after_success:
  - coveralls